language: go

go:
  - 1.7.4
  - tip
  
matrix:
  fast_finish: true
  allow_failures:
  - go: tip

sudo: true

before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y && sudo apt-get update -q
  - sudo apt-get install glide -y
  - curl -L  https://github.com/coreos/etcd/releases/download/v2.3.7/etcd-v2.3.7-linux-amd64.tar.gz -o etcd-v2.3.7-linux-amd64.tar.gz
  - tar xzvf etcd-v2.3.7-linux-amd64.tar.gz
  - ./etcd-v2.3.7-linux-amd64/etcd &

before_script:
  - make deps

script:
  - make test
  - make vet
  - make fmt

after_success:
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN; fi'
