language: go
go:
  - 1.15.x
  - tip

matrix:
  fast_finish: true
  allow_failures:
  - go: tip

services:
  - docker

script:
  - make test
  - make lint

after_success:
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN; fi'
