language: go
go:
  - 1.12.11
  - tip

matrix:
  fast_finish: true
  allow_failures:
  - go: tip

sudo: true

before_install:
  - curl -L  https://github.com/coreos/etcd/releases/download/v3.3.3/etcd-v3.3.3-linux-amd64.tar.gz -o etcd-v3.3.3-linux-amd64.tar.gz
  - tar xzvf etcd-v3.3.3-linux-amd64.tar.gz
  - ./etcd-v3.3.3-linux-amd64/etcd &

script:
  - make test
  - make vet
  - make fmt

after_success:
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN; fi'
